// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: lyrics.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import EeveeSwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum SyncTypeEnum: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case unsynced // = 0
  case lineSynced // = 1
  case syllableSynced // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unsynced
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unsynced
    case 1: self = .lineSynced
    case 2: self = .syllableSynced
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unsynced: return 0
    case .lineSynced: return 1
    case .syllableSynced: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }
}

#if swift(>=4.2)

extension SyncTypeEnum: CaseIterable {
  static let allCases: [SyncTypeEnum] = [
    .unsynced,
    .lineSynced,
    .syllableSynced,
  ]
}

#endif

struct Syllable {
  var startTimeMs: Int64 = 0
  var numChars: Int64 = 0
  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct LyricsLine {
  var startTimeMs: Int64 = 0
  var words: String = String()
  var syllables: [Syllable] = []
  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct ColorData {
  var background: Int32 = 0
  var text: Int32 = 0
  var highlightText: Int32 = 0
  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct AlternativeLanguages {
  var language: String = String()
  var lines: [String] = []
  var isRtlLanguage: Bool = false
  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct LyricsResponse {
  var syncType: SyncTypeEnum = .unsynced
  var lines: [LyricsLine] = []
  var provider: String = String()
  var providerLyricsId: String = String()
  var providerDisplayName: String = String()
  var syncLyricsUri: String = String()
  var isDenseTypeface: Bool = false
  var alternatives: [AlternativeLanguages] = []
  var language: String = String()
  var isRtlLanguage: Bool = false
  var fullscreenAction: Int32 = 0
  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct ColorLyricsResponse {
  var lyrics: LyricsResponse {
    get {return _lyrics ?? LyricsResponse()}
    set {_lyrics = newValue}
  }
  var colors: ColorData {
    get {return _colors ?? ColorData()}
    set {_colors = newValue}
  }
  var hasVocalRemoval: Bool = false
  var vocalRemovalColors: ColorData {
    get {return _vocalRemovalColors ?? ColorData()}
    set {_vocalRemovalColors = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _lyrics: LyricsResponse? = nil
  fileprivate var _colors: ColorData? = nil
  fileprivate var _vocalRemovalColors: ColorData? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension SyncTypeEnum: @unchecked Sendable {}
extension Syllable: @unchecked Sendable {}
extension LyricsLine: @unchecked Sendable {}
extension ColorData: @unchecked Sendable {}
extension AlternativeLanguages: @unchecked Sendable {}
extension LyricsResponse: @unchecked Sendable {}
extension ColorLyricsResponse: @unchecked Sendable {}
#endif

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension SyncTypeEnum: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNSYNCED"),
    1: .same(proto: "LINE_SYNCED"),
    2: .same(proto: "SYLLABLE_SYNCED"),
  ]
}

extension Syllable: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Syllable"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "startTimeMs"),
    2: .same(proto: "numChars"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.startTimeMs) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.numChars) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startTimeMs != 0 {
      try visitor.visitSingularInt64Field(value: self.startTimeMs, fieldNumber: 1)
    }
    if self.numChars != 0 {
      try visitor.visitSingularInt64Field(value: self.numChars, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Syllable, rhs: Syllable) -> Bool {
    if lhs.startTimeMs != rhs.startTimeMs {return false}
    if lhs.numChars != rhs.numChars {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LyricsLine: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LyricsLine"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "startTimeMs"),
    2: .same(proto: "words"),
    3: .same(proto: "syllables"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.startTimeMs) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.words) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.syllables) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startTimeMs != 0 {
      try visitor.visitSingularInt64Field(value: self.startTimeMs, fieldNumber: 1)
    }
    if !self.words.isEmpty {
      try visitor.visitSingularStringField(value: self.words, fieldNumber: 2)
    }
    if !self.syllables.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.syllables, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LyricsLine, rhs: LyricsLine) -> Bool {
    if lhs.startTimeMs != rhs.startTimeMs {return false}
    if lhs.words != rhs.words {return false}
    if lhs.syllables != rhs.syllables {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ColorData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ColorData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "background"),
    2: .same(proto: "text"),
    3: .same(proto: "highlightText"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.background) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.text) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.highlightText) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.background != 0 {
      try visitor.visitSingularInt32Field(value: self.background, fieldNumber: 1)
    }
    if self.text != 0 {
      try visitor.visitSingularInt32Field(value: self.text, fieldNumber: 2)
    }
    if self.highlightText != 0 {
      try visitor.visitSingularInt32Field(value: self.highlightText, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ColorData, rhs: ColorData) -> Bool {
    if lhs.background != rhs.background {return false}
    if lhs.text != rhs.text {return false}
    if lhs.highlightText != rhs.highlightText {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AlternativeLanguages: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AlternativeLanguages"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "language"),
    2: .same(proto: "lines"),
    3: .same(proto: "isRtlLanguage"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.language) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.lines) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isRtlLanguage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.language.isEmpty {
      try visitor.visitSingularStringField(value: self.language, fieldNumber: 1)
    }
    if !self.lines.isEmpty {
      try visitor.visitRepeatedStringField(value: self.lines, fieldNumber: 2)
    }
    if self.isRtlLanguage != false {
      try visitor.visitSingularBoolField(value: self.isRtlLanguage, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AlternativeLanguages, rhs: AlternativeLanguages) -> Bool {
    if lhs.language != rhs.language {return false}
    if lhs.lines != rhs.lines {return false}
    if lhs.isRtlLanguage != rhs.isRtlLanguage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LyricsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LyricsResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "syncType"),
    2: .same(proto: "lines"),
    3: .same(proto: "provider"),
    4: .same(proto: "providerLyricsId"),
    5: .same(proto: "providerDisplayName"),
    7: .same(proto: "syncLyricsUri"),
    8: .same(proto: "isDenseTypeface"),
    9: .same(proto: "alternatives"),
    10: .same(proto: "language"),
    11: .same(proto: "isRtlLanguage"),
    12: .same(proto: "fullscreenAction"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.syncType) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.lines) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.provider) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.providerLyricsId) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.providerDisplayName) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.syncLyricsUri) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.isDenseTypeface) }()
      case 9: try { try decoder.decodeRepeatedMessageField(value: &self.alternatives) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.language) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self.isRtlLanguage) }()
      case 12: try { try decoder.decodeSingularInt32Field(value: &self.fullscreenAction) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.syncType != .unsynced {
      try visitor.visitSingularEnumField(value: self.syncType, fieldNumber: 1)
    }
    if !self.lines.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.lines, fieldNumber: 2)
    }
    if !self.provider.isEmpty {
      try visitor.visitSingularStringField(value: self.provider, fieldNumber: 3)
    }
    if !self.providerLyricsId.isEmpty {
      try visitor.visitSingularStringField(value: self.providerLyricsId, fieldNumber: 4)
    }
    if !self.providerDisplayName.isEmpty {
      try visitor.visitSingularStringField(value: self.providerDisplayName, fieldNumber: 5)
    }
    if !self.syncLyricsUri.isEmpty {
      try visitor.visitSingularStringField(value: self.syncLyricsUri, fieldNumber: 7)
    }
    if self.isDenseTypeface != false {
      try visitor.visitSingularBoolField(value: self.isDenseTypeface, fieldNumber: 8)
    }
    if !self.alternatives.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.alternatives, fieldNumber: 9)
    }
    if !self.language.isEmpty {
      try visitor.visitSingularStringField(value: self.language, fieldNumber: 10)
    }
    if self.isRtlLanguage != false {
      try visitor.visitSingularBoolField(value: self.isRtlLanguage, fieldNumber: 11)
    }
    if self.fullscreenAction != 0 {
      try visitor.visitSingularInt32Field(value: self.fullscreenAction, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LyricsResponse, rhs: LyricsResponse) -> Bool {
    if lhs.syncType != rhs.syncType {return false}
    if lhs.lines != rhs.lines {return false}
    if lhs.provider != rhs.provider {return false}
    if lhs.providerLyricsId != rhs.providerLyricsId {return false}
    if lhs.providerDisplayName != rhs.providerDisplayName {return false}
    if lhs.syncLyricsUri != rhs.syncLyricsUri {return false}
    if lhs.isDenseTypeface != rhs.isDenseTypeface {return false}
    if lhs.alternatives != rhs.alternatives {return false}
    if lhs.language != rhs.language {return false}
    if lhs.isRtlLanguage != rhs.isRtlLanguage {return false}
    if lhs.fullscreenAction != rhs.fullscreenAction {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ColorLyricsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ColorLyricsResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "lyrics"),
    2: .same(proto: "colors"),
    3: .same(proto: "hasVocalRemoval"),
    4: .same(proto: "vocalRemovalColors"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._lyrics) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._colors) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.hasVocalRemoval) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._vocalRemovalColors) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._lyrics {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if let v = self._colors {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    if self.hasVocalRemoval != false {
      try visitor.visitSingularBoolField(value: self.hasVocalRemoval, fieldNumber: 3)
    }
    if let v = self._vocalRemovalColors {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ColorLyricsResponse, rhs: ColorLyricsResponse) -> Bool {
    if lhs._lyrics != rhs._lyrics {return false}
    if lhs._colors != rhs._colors {return false}
    if lhs.hasVocalRemoval != rhs.hasVocalRemoval {return false}
    if lhs._vocalRemovalColors != rhs._vocalRemovalColors {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
